//! FFI boundary registry.
//!
//! In a hybrid transpile (e.g. Python + C extension, Python + CUDA
//! kernel), the agent must know exactly which symbols cross language
//! lines and what their Rust shim signatures should be. This crate is
//! the single source of truth for that mapping within a session.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::Path;
use xpile_meta_hir::{FfiBoundary, Function, Item, Module, SourceLang, Type};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct FfiManifest {
    pub entries: Vec<FfiEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FfiEntry {
    pub symbol: String,
    pub from_lang: SourceLang,
    pub to_lang: SourceLang,
    pub source_signature: String,
    pub rust_shim_signature: String,
    pub shim_id: String,
}

/// PMAT-894 (Sprint-2 Tier 2): a cross-language FFI boundary could not be paired
/// with a defining module during [`FfiManifest::reconcile`]. This is the
/// manifest-completeness failure of `C-FFI-CPYTHON-EXT` (the contract's
/// `manifest_completeness` equation): in a hybrid transpile EVERY boundary that
/// crosses a language line must resolve, or the hybrid build cannot be emitted.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FfiReconcileError {
    pub unresolved: Vec<String>,
}

impl std::fmt::Display for FfiReconcileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "FFI reconciliation failed — {} unresolved boundary(ies): {}",
            self.unresolved.len(),
            self.unresolved.join("; ")
        )
    }
}

impl std::error::Error for FfiReconcileError {}

/// PMAT-899 (Sprint-2 Tier 2): a reconciled boundary could not be lowered to a
/// Rust FFI shim because a recovered parameter/return type has no ABI-honest C
/// mapping (a pointer/string/struct/container the first-cut emitter refuses
/// rather than mis-marshal). Mirrors [`FfiReconcileError`]: surfacing the gap
/// beats emitting a wrong-ABI shim.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FfiEmitError {
    pub unsupported: Vec<String>,
}

impl std::fmt::Display for FfiEmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "FFI shim emission failed — {} unsupported boundary(ies): {}",
            self.unsupported.len(),
            self.unsupported.join("; ")
        )
    }
}

impl std::error::Error for FfiEmitError {}

/// PMAT-901 (Sprint-2 Day 2): emitting a buildable hybrid Cargo workspace
/// failed — either a filesystem error or the shim-emission gap
/// ([`FfiEmitError`], surfaced unchanged so an unshimmable boundary still fails
/// loud rather than producing a half-built workspace).
#[derive(Debug)]
pub enum WorkspaceEmitError {
    Io(std::io::Error),
    Shims(FfiEmitError),
}

impl std::fmt::Display for WorkspaceEmitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            WorkspaceEmitError::Io(e) => write!(f, "hybrid workspace I/O error: {e}"),
            WorkspaceEmitError::Shims(e) => write!(f, "{e}"),
        }
    }
}

impl std::error::Error for WorkspaceEmitError {}

impl From<std::io::Error> for WorkspaceEmitError {
    fn from(e: std::io::Error) -> Self {
        WorkspaceEmitError::Io(e)
    }
}

impl From<FfiEmitError> for WorkspaceEmitError {
    fn from(e: FfiEmitError) -> Self {
        WorkspaceEmitError::Shims(e)
    }
}

/// PMAT-901: the `build.rs` emitted into a hybrid workspace. std-only: it
/// `cc`-compiles every `csrc/*.c` to an object and links it directly into the
/// binary via `cargo:rustc-link-arg`, so the emitted `extern "C"` shims resolve
/// against the real C symbols at link time (objects passed directly are fully
/// included — no archive/`ar` needed).
const HYBRID_BUILD_RS: &str = r#"// Generated by xpile hybrid (Phase 5a) — do not edit.
fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let csrc = std::path::Path::new(&manifest).join("csrc");
    let entries = match std::fs::read_dir(&csrc) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("c") {
            continue;
        }
        let stem = path.file_stem().unwrap().to_string_lossy().to_string();
        let obj = format!("{out_dir}/{stem}.o");
        let status = std::process::Command::new("cc")
            .arg("-c")
            .arg(&path)
            .arg("-o")
            .arg(&obj)
            .status()
            .expect("spawn cc");
        assert!(status.success(), "cc failed on {}", path.display());
        println!("cargo:rustc-link-arg={obj}");
        println!("cargo:rerun-if-changed={}", path.display());
    }
}
"#;

/// Deterministic, dependency-free shim id (FNV-1a hex over the boundary's
/// identifying fields). Stable across runs so a manifest entry — and the shim it
/// names — is reproducible. (The spec's sha256 is a later hardening; FNV-1a is
/// sufficient for in-session uniqueness and is std-only.)
/// PMAT-895 (Sprint-2 Tier 2): the externally-callable name a module item
/// exports — what an incoming FFI boundary's `symbol` must match. A callable FFI
/// symbol is a function; a module-level constant is also addressable. Structs/
/// enums are types, not call targets, so they don't export an FFI symbol.
fn item_exported_name(item: &Item) -> Option<&str> {
    match item {
        Item::Function(f) => Some(&f.name),
        Item::Const { name, .. } => Some(name),
        _ => None,
    }
}

fn shim_id(b: &FfiBoundary) -> String {
    let key = format!(
        "{:?}->{:?}:{}:{}",
        b.from_lang, b.to_lang, b.symbol, b.signature
    );
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in key.as_bytes() {
        h ^= *byte as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("shim_{h:016x}")
}

impl FfiManifest {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn register(&mut self, entry: FfiEntry) {
        self.entries.push(entry);
    }

    /// Phase 2 of the hybrid transpile flow (`hybrid-transpile-flow.md` §16):
    /// reconcile every cross-language FFI boundary across the dispatched modules
    /// into a single manifest, or fail listing the unresolved boundaries.
    ///
    /// A boundary `{from_lang, to_lang, symbol, signature}` is a call that
    /// crosses from `from_lang` into `to_lang`. It RESOLVES when a sibling module
    /// of `to_lang` is present in the dispatched set (the target language was
    /// actually transpiled). Each resolved boundary becomes an [`FfiEntry`] with a
    /// deterministic `shim_id`; any boundary whose target language is absent fails
    /// reconciliation (the `manifest_completeness` invariant of
    /// `C-FFI-CPYTHON-EXT`). Same-language boundaries (`from == to`) are no-ops.
    ///
    /// PMAT-895: resolution is SYMBOL-LEVEL — a boundary resolves only when a
    /// module of `to_lang` actually DEFINES an item (function/const) named
    /// `symbol`. A target-language module that is present but does NOT export the
    /// symbol still fails reconciliation (the `manifest_completeness` invariant is
    /// about the symbol crossing the line, not just the language being present).
    pub fn reconcile(modules: &[Module]) -> Result<FfiManifest, FfiReconcileError> {
        let mut manifest = FfiManifest::new();
        let mut unresolved = Vec::new();
        for module in modules {
            for b in &module.ffi_boundaries {
                if b.from_lang == b.to_lang {
                    continue; // not a cross-language boundary
                }
                let lang_present = modules.iter().any(|m| m.source_lang == b.to_lang);
                let symbol_defined = modules.iter().any(|m| {
                    m.source_lang == b.to_lang
                        && m.items
                            .iter()
                            .any(|it| item_exported_name(it) == Some(b.symbol.as_str()))
                });
                if symbol_defined {
                    manifest.register(FfiEntry {
                        symbol: b.symbol.clone(),
                        from_lang: b.from_lang,
                        to_lang: b.to_lang,
                        source_signature: b.signature.clone(),
                        // First-cut shim signature: the real C/PyObject → Rust
                        // lowering is a later increment; record a stable placeholder
                        // that names the symbol so downstream emission can key on it.
                        rust_shim_signature: format!("fn {}(/* {} */)", b.symbol, b.signature),
                        shim_id: shim_id(b),
                    });
                } else {
                    // Distinguish "no target-language module at all" from "module
                    // present but symbol not exported" — both block the hybrid
                    // build, but the diagnostic should point at the right fix.
                    let reason = if lang_present {
                        format!("no {:?} module defines `{}`", b.to_lang, b.symbol)
                    } else {
                        format!("no {:?} module in the dispatched set", b.to_lang)
                    };
                    unresolved.push(format!(
                        "{:?}->{:?} `{}` ({}): {}",
                        b.from_lang, b.to_lang, b.symbol, b.signature, reason
                    ));
                }
            }
        }
        if unresolved.is_empty() {
            Ok(manifest)
        } else {
            Err(FfiReconcileError { unresolved })
        }
    }

    /// PMAT-899 — Phase 4 of the hybrid flow (`hybrid-transpile-flow.md` §16):
    /// emit a self-contained Rust FFI shim file for every reconciled
    /// cross-language boundary, dispatched per target paradigm. `modules` is the
    /// same set passed to [`reconcile`](Self::reconcile) — it is the ONLY source
    /// of real param/return types (an [`FfiEntry`] carries placeholder
    /// signatures).
    ///
    /// Per-paradigm strategy (see [`shim_part_for`]):
    ///   - **C** → a real `extern "C"` foreign declaration + a safe `*_shim`
    ///     wrapper confining `unsafe`, citing `C-FFI-CPYTHON-EXT`.
    ///   - **Shell** → a real `std::process::Command`-based wrapper (shell speaks
    ///     argv + exit codes — no C ABI, no `unsafe`), citing
    ///     `C-FFI-SHELL-SUBPROCESS`.
    ///   - **Ruchy / Rust** → a real same-crate direct-call forwarder (both lower
    ///     to native Rust in the same crate — a plain in-crate call, no `unsafe`,
    ///     no `extern`). Four of six arms are now real (C, Shell, Ruchy, Rust).
    ///   - **Cpp / Cuda / Python / Lean** → a specific, mechanism-named
    ///     [`FfiEmitError`] (pybind11 / cuda_kernel / pyo3 / proof-lane) so the
    ///     remaining gaps stay actionable, never silently dropped or mis-emitted.
    ///
    /// All-or-nothing (mirrors `reconcile`'s `manifest_completeness`): if ANY
    /// boundary cannot be shimmed, nothing is emitted and the gaps are returned —
    /// a half-shimmed hybrid build is not a build.
    ///
    /// Compile-checkable WITHOUT the foreign object: a C extern symbol stays
    /// unresolved at lib-build time and a shell shim needs no symbol at all, so
    /// type/arity/ABI are validated by `rustc --crate-type lib` alone (linking is
    /// only needed to *run*).
    pub fn emit_rust_shims(&self, modules: &[Module]) -> Result<String, FfiEmitError> {
        let mut unsupported = Vec::new();
        let mut extern_lines = Vec::new();
        let mut wrappers = Vec::new();
        let mut contracts: Vec<&'static str> = Vec::new();

        for entry in &self.entries {
            match shim_part_for(entry, modules) {
                Ok(part) => {
                    extern_lines.extend(part.extern_decl);
                    wrappers.push(part.wrapper);
                    if let Some(c) = part.contract {
                        if !contracts.contains(&c) {
                            contracts.push(c);
                        }
                    }
                }
                Err(reasons) => unsupported.extend(reasons),
            }
        }

        if !unsupported.is_empty() {
            return Err(FfiEmitError { unsupported });
        }

        let mut out = String::new();
        out.push_str("// Generated by xpile hybrid (Phase 4) — do not edit.\n");
        out.push_str("// FFI shims recovered from the reconciled manifest.\n");
        for c in &contracts {
            out.push_str(&format!("// xpile-contract: {c}\n"));
        }
        if !extern_lines.is_empty() {
            out.push_str("// ABI note: C `int` lowers to meta-HIR Type::I64 -> c_int (32-bit),\n");
            out.push_str("//   while `long`/`int64_t` lower to the distinct Type::CLong width\n");
            out.push_str(
                "//   -> c_longlong (64-bit), not narrowed to c_int (PMAT-909). Float /\n",
            );
            out.push_str(
                "//   pointer / string ABI tokens are the remaining decy lexer ceiling.\n",
            );
        }
        out.push_str("#![allow(dead_code)]\n");
        if !extern_lines.is_empty() {
            // `unsafe extern "C"` (not bare `extern "C"`): a bare extern block is
            // a hard error under Rust edition 2024 (`extern blocks must be
            // unsafe`), and `cargo new` has defaulted to edition 2024 since Rust
            // 1.85. `unsafe extern` compiles cleanly under 2021 AND 2024, so the
            // emitted file stays valid in whatever crate the user drops it into.
            out.push_str("\nunsafe extern \"C\" {\n");
            out.push_str(&extern_lines.join("\n"));
            out.push('\n');
            out.push_str("}\n");
        }
        for w in &wrappers {
            out.push('\n');
            out.push_str(w);
        }
        Ok(out)
    }

    /// PMAT-901 — Phase 5a of the hybrid flow (`hybrid-transpile-flow.md` §16):
    /// emit a self-contained, BUILDABLE Cargo workspace for the hybrid module.
    /// Files: `Cargo.toml` (a bin crate); `build.rs` ([`HYBRID_BUILD_RS`] —
    /// cc-compiles every `csrc/*.c` and links it); `csrc/<name>.c` (each C source
    /// verbatim, from `c_sources`); `src/ffi_shims.rs` (the reconciled shims from
    /// [`emit_rust_shims`](Self::emit_rust_shims)); and `src/main.rs` (`rust_src`,
    /// the caller's lowering of the non-C modules, plus `mod ffi_shims;`).
    ///
    /// `cargo build` on the result compiles the Rust side AND cc-compiles + links
    /// the C side through the emitted `extern "C"` shim — the first *executing*
    /// hybrid artifact (Phase 5a). `rust_src` is supplied by the caller (the rust
    /// backend's lowering of the entry module) so this crate stays codegen-free.
    /// All-or-nothing: an unshimmable boundary fails via [`FfiEmitError`] before
    /// anything is written past the shim step.
    pub fn emit_hybrid_workspace(
        &self,
        modules: &[Module],
        c_sources: &[(String, String)],
        rust_src: &str,
        out_dir: &Path,
    ) -> Result<(), WorkspaceEmitError> {
        // Fail loud on an unshimmable boundary BEFORE touching the filesystem.
        let shims = self.emit_rust_shims(modules)?;

        std::fs::create_dir_all(out_dir.join("src"))?;
        std::fs::create_dir_all(out_dir.join("csrc"))?;
        std::fs::write(
            out_dir.join("Cargo.toml"),
            "[package]\nname = \"xpile-hybrid-artifact\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n[dependencies]\n",
        )?;
        std::fs::write(out_dir.join("build.rs"), HYBRID_BUILD_RS)?;
        for (name, content) in c_sources {
            std::fs::write(out_dir.join("csrc").join(name), content)?;
        }
        std::fs::write(out_dir.join("src").join("ffi_shims.rs"), &shims)?;
        // PMAT-902: bridge the lowered call names to the emitted shims. The Python
        // frontend lowers a boundary call `square_sum(7)` to a plain `square_sum(7)`,
        // but the safe wrapper is `ffi_shims::square_sum_shim`. A per-boundary
        // `use ffi_shims::<sym>_shim as <sym>;` makes the lowered call resolve to
        // the shim, so an `app.py` `main()` that actually invokes the C side links
        // and runs (the executing north-star artifact). `allow(unused_imports)`
        // keeps a `pass`-bodied `main()` (no boundary call) warning-free.
        let mut aliases = String::new();
        for e in &self.entries {
            aliases.push_str(&format!(
                "#[allow(unused_imports)]\nuse ffi_shims::{0}_shim as {0};\n",
                e.symbol
            ));
        }
        std::fs::write(
            out_dir.join("src").join("main.rs"),
            format!("mod ffi_shims;\n{aliases}\n{rust_src}\n"),
        )?;
        Ok(())
    }
}

/// One emitted boundary's contribution to the shim file: an optional
/// `extern "C"` foreign declaration (C boundaries only), the safe wrapper, and
/// the contract it cites (if a contract governs the strategy yet).
struct ShimPart {
    extern_decl: Option<String>,
    wrapper: String,
    contract: Option<&'static str>,
}

/// Exhaustive per-`to_lang` shim strategy. Every paradigm xpile knows is
/// classified here — a real shim or a specific, mechanism-named gap — and a new
/// [`SourceLang`] variant fails to compile until it is too (no wildcard arm).
/// "Surface the gap" beats "mis-emit a wrong shim". Returns every failure reason
/// for the boundary so the caller can report them all at once.
fn shim_part_for(entry: &FfiEntry, modules: &[Module]) -> Result<ShimPart, Vec<String>> {
    match entry.to_lang {
        // Real, ABI-honest C-extension shim — the canonical CPython path.
        SourceLang::C => match defining_function(modules, entry) {
            Some(f) => emit_c_shim(entry, f),
            None => Err(vec![format!(
                "{}: resolved to a C symbol that is not a function (a const?) — \
                 cannot emit a call shim",
                entry.symbol
            )]),
        },
        // Real subprocess shim — shell speaks argv + exit codes, which
        // std::process::Command models exactly (no C ABI, no `unsafe`).
        SourceLang::Shell => Ok(emit_shell_shim(entry)),
        // Recognized boundaries whose binding mechanism is not yet emitted. Each
        // names the real mechanism + roadmap phase so the gap is actionable.
        SourceLang::Cpp => Err(vec![format!(
            "{}: C++ boundary → needs a pybind11 shim (the symbol is name-mangled; \
             raw `extern \"C\"` would mis-link) — roadmap Phase 7+",
            entry.symbol
        )]),
        SourceLang::Cuda => Err(vec![format!(
            "{}: CUDA boundary → needs a host-launch shim (cudaLaunchKernel \
             marshalling), not a direct call — roadmap Phase 7+",
            entry.symbol
        )]),
        SourceLang::Python => Err(vec![format!(
            "{}: Python boundary → needs a pyo3 shim (Ruchy↔Python / CPython \
             embedding) — roadmap Phase 6",
            entry.symbol
        )]),
        // Real same-crate direct-call forwarder. Ruchy lowers to Rust and a Rust
        // boundary is already Rust, so both land in the SAME emitted crate — a
        // boundary call is a plain in-crate call, not FFI (no C ABI, no `unsafe`,
        // no `extern` block). A missing defining function is the same internal
        // invariant violation `reconcile` guards as for the C arm.
        SourceLang::Ruchy | SourceLang::Rust => match defining_function(modules, entry) {
            Some(f) => emit_direct_shim(entry, f),
            None => Err(vec![format!(
                "{}: resolved to a {:?} symbol that is not a function — cannot emit \
                 a direct-call shim",
                entry.symbol, entry.to_lang
            )]),
        },
        SourceLang::Lean => Err(vec![format!(
            "{}: Lean is the proof lane, not a runtime FFI target — a Lean boundary \
             is a proof obligation, not a runtime shim",
            entry.symbol
        )]),
    }
}

/// Emit a real C-extension shim: an `extern "C"` foreign declaration (symbol +
/// ABI-honest arity) and a safe `*_shim` wrapper confining `unsafe`. Returns
/// every ABI-mapping failure (each param + the return) so they can be reported
/// together rather than one at a time.
fn emit_c_shim(entry: &FfiEntry, f: &Function) -> Result<ShimPart, Vec<String>> {
    let mut unsupported = Vec::new();
    let mut extern_params = Vec::new();
    let mut wrap_params = Vec::new();
    let mut call_args = Vec::new();
    for p in &f.params {
        match c_abi_type(&p.ty) {
            Some(cty) => {
                extern_params.push(format!("{}: {}", p.name, cty));
                wrap_params.push(format!("{}: {}", p.name, wrapper_native(&p.ty)));
                call_args.push(format!("{} as {}", p.name, cty));
            }
            None => unsupported.push(format!(
                "{}: parameter `{}` type {:?} is not ABI-mappable to C",
                entry.symbol, p.name, p.ty
            )),
        }
    }

    // Return position: Type::Unit is C `void` (no `-> T`); anything else must
    // map, or the boundary is refused.
    let (extern_ret, wrap_ret_sig, wrap_ret_expr) = match &f.return_type {
        Type::Unit => (String::new(), String::new(), None),
        ty => match c_abi_type(ty) {
            Some(cty) => {
                let nat = wrapper_native(ty);
                (
                    format!(" -> {cty}"),
                    format!(" -> {nat}"),
                    Some(format!("__r as {nat}")),
                )
            }
            None => {
                unsupported.push(format!(
                    "{}: return type {:?} is not ABI-mappable to C",
                    entry.symbol, ty
                ));
                (String::new(), String::new(), None)
            }
        },
    };

    if !unsupported.is_empty() {
        return Err(unsupported);
    }

    let extern_decl = format!(
        "    // {}: {:?} -> {:?}\n    fn {}({}){};",
        entry.shim_id,
        entry.from_lang,
        entry.to_lang,
        entry.symbol,
        extern_params.join(", "),
        extern_ret
    );
    let call = format!("{}({})", entry.symbol, call_args.join(", "));
    let body = match wrap_ret_expr {
        Some(ret) => format!("    let __r = unsafe {{ {call} }};\n    {ret}\n"),
        None => format!("    unsafe {{ {call} }}\n"),
    };
    let wrapper = format!(
        "/// Safe wrapper for `{}` — confines `unsafe`; callers speak i64/f64.\npub fn {}_shim({}){} {{\n{}}}\n",
        entry.symbol,
        entry.symbol,
        wrap_params.join(", "),
        wrap_ret_sig,
        body
    );
    Ok(ShimPart {
        extern_decl: Some(extern_decl),
        wrapper,
        contract: Some("C-FFI-CPYTHON-EXT"),
    })
}

/// Emit a real shell-subprocess shim. A shell boundary speaks argv strings + an
/// exit code — exactly `std::process::Command`'s model — so the shim is a safe,
/// `unsafe`-free wrapper that runs the transpiled POSIX symbol as a subprocess
/// (the bashrs lane emits the script; this is the calling site that crosses into
/// it). No `extern "C"` block: shell is not a C-ABI callee. Cites
/// `C-FFI-SHELL-SUBPROCESS` (PMAT-907) — the argv-passthrough + exit-code-
/// propagation contract governing this strategy, the calling-site companion of
/// `C-BASHRS-POSIX-IDEMPOTENCE` (which governs the emitted shell *script*).
fn emit_shell_shim(entry: &FfiEntry) -> ShimPart {
    let wrapper = format!(
        "/// Shell boundary `{0}` — runs the transpiled POSIX symbol as a subprocess.\n/// Shell speaks argv + exit codes, so the shim takes `&[&str]` args and returns\n/// the captured `Output` (no `unsafe`, no C ABI).\npub fn {0}_shim(args: &[&str]) -> ::std::io::Result<::std::process::Output> {{\n    ::std::process::Command::new(\"{0}\").args(args).output()\n}}\n",
        entry.symbol
    );
    ShimPart {
        extern_decl: None,
        wrapper,
        contract: Some("C-FFI-SHELL-SUBPROCESS"),
    }
}

/// Emit a real **same-crate direct-call forwarder** for a Ruchy or Rust
/// boundary. Ruchy lowers to Rust and a Rust boundary is already Rust, so both
/// callees are native Rust functions in the SAME emitted crate — a boundary here
/// is a plain in-crate call, not FFI. The shim is therefore a thin, safe wrapper
/// that forwards to `symbol` with its native Rust signature: **no `extern "C"`
/// block, no `unsafe`, no ABI marshalling** (contrast [`emit_c_shim`], which must
/// cross the C ABI). Returns every non-native-mappable param/return reason
/// together so the caller reports them all at once (mirrors [`emit_c_shim`]).
/// Capability-ahead-of-contract — a direct call needs no FFI substrate, so
/// `contract` is `None` (like the shell arm).
fn emit_direct_shim(entry: &FfiEntry, f: &Function) -> Result<ShimPart, Vec<String>> {
    let mut unsupported = Vec::new();
    let mut params = Vec::new();
    let mut args = Vec::new();
    for p in &f.params {
        match direct_native_type(&p.ty) {
            Ok(rty) => {
                params.push(format!("{}: {}", p.name, rty));
                args.push(p.name.clone());
            }
            Err(reason) => {
                unsupported.push(format!("{}: parameter `{}` {reason}", entry.symbol, p.name))
            }
        }
    }

    // Return position: `Type::Unit` is a bare `()` (no `-> T`), matching the rust
    // backend; anything else must map to a native Rust type or the boundary is
    // refused.
    let ret_sig = match &f.return_type {
        Type::Unit => String::new(),
        ty => match direct_native_type(ty) {
            Ok(rty) => format!(" -> {rty}"),
            Err(reason) => {
                unsupported.push(format!("{}: return type {reason}", entry.symbol));
                String::new()
            }
        },
    };

    if !unsupported.is_empty() {
        return Err(unsupported);
    }

    let wrapper = format!(
        "/// Same-crate direct-call forwarder for `{0}` ({1:?} lowers to Rust — a\n\
         /// boundary here is a plain in-crate call, not a foreign-function call).\n\
         pub fn {0}_shim({2}){3} {{\n    {0}({4})\n}}\n",
        entry.symbol,
        entry.to_lang,
        params.join(", "),
        ret_sig,
        args.join(", ")
    );
    Ok(ShimPart {
        extern_decl: None,
        wrapper,
        contract: None,
    })
}

/// Native Rust type a **same-crate direct-call** shim speaks for a meta-HIR
/// [`Type`]. Unlike [`c_abi_type`] there is NO C ABI to honor (the callee is
/// native Rust in the same crate), so the accepted set is wider — it mirrors what
/// `xpile-rust-codegen` emits for a signature, but only for the **dependency-free
/// std** types, because the emitted hybrid workspace pins `[dependencies]` empty.
/// Types whose Rust lowering needs an external crate (`BigInt` →
/// `xpile_bigint`, `Dict` → `indexmap`) or a co-emitted definition (`Struct`) are
/// refused with a named reason rather than emitting an unbuildable forwarder; the
/// bashrs-domain types are refused as the rust backend refuses them. A `Unit`
/// parameter is nonsensical (Unit is a return-only shape, handled by the caller).
fn direct_native_type(ty: &Type) -> Result<String, String> {
    Ok(match ty {
        Type::I64 => "i64".to_string(),
        // PMAT-909: a C `long`/`int64_t` is value-compatible with I64 in a
        // native (no-C-ABI) direct call — both speak `i64`.
        Type::CLong => "i64".to_string(),
        Type::F64 => "f64".to_string(),
        Type::Bool => "bool".to_string(),
        Type::Str => "String".to_string(),
        Type::List(elem) => format!("Vec<{}>", direct_native_type(elem)?),
        Type::Set(elem) => format!("std::collections::HashSet<{}>", direct_native_type(elem)?),
        Type::Optional(inner) => format!("Option<{}>", direct_native_type(inner)?),
        Type::Tuple(elems) => {
            let mut parts = Vec::with_capacity(elems.len());
            for e in elems {
                parts.push(direct_native_type(e)?);
            }
            // A 1-tuple needs the trailing comma — `(T,)` — to stay a tuple.
            if parts.len() == 1 {
                format!("({},)", parts[0])
            } else {
                format!("({})", parts.join(", "))
            }
        }
        Type::Unit => {
            return Err("type `()` is only valid in return position".to_string());
        }
        Type::BigInt => {
            return Err(
                "type BigInt lowers to xpile_bigint::BigInt — a non-std dep the \
                        hybrid workspace does not pin; direct-call shim refuses it"
                    .to_string(),
            );
        }
        Type::Dict(_, _) => {
            return Err(
                "type Dict lowers to indexmap::IndexMap — a non-std dep the \
                        hybrid workspace does not pin; direct-call shim refuses it"
                    .to_string(),
            );
        }
        Type::Struct(name) => {
            return Err(format!(
                "struct type `{name}` needs its definition co-emitted into the shim crate \
                 — direct-call shim refuses it until struct re-export lands"
            ));
        }
        Type::ShellString | Type::ExitCode => {
            return Err(format!(
                "type {ty:?} is a bashrs-domain type (contract C-BASHRS-POSIX-IDEMPOTENCE) \
                 — not a direct-call shim target"
            ));
        }
    })
}

/// Recover the real defining [`Function`] for a reconciled entry, mirroring
/// [`FfiManifest::reconcile`]'s symbol/`to_lang` match. `reconcile` guarantees an
/// entry exists only when the symbol is defined, so a miss here is an internal
/// invariant violation (surfaced as an unsupported boundary by the caller).
/// The defining function for a reconciled boundary: the `Item::Function` named
/// `entry.symbol` in the module whose `source_lang` is `entry.to_lang`. Public so
/// the `--verify` flow (PMAT-902) can read the C callee's param/return types to
/// build the CPython-side ctypes ABI binding for the differential reference.
pub fn defining_function<'a>(modules: &'a [Module], entry: &FfiEntry) -> Option<&'a Function> {
    for m in modules {
        if m.source_lang != entry.to_lang {
            continue;
        }
        for it in &m.items {
            if let Item::Function(f) = it {
                if f.name == entry.symbol {
                    return Some(f);
                }
            }
        }
    }
    None
}

/// ABI-honest meta-HIR `Type` → Rust FFI type for a `to_lang == C` boundary.
/// Returns `None` for types the first cut refuses (pointer/string/container/
/// struct) rather than mis-marshal.
///
/// DECY-FIDELITY CEILING (PMAT-909 partial lift): decy models C `int` (a
/// 32-bit type) as `Type::I64`, so `I64 → c_int` keeps that boundary
/// 32-bit-honest. A genuine C `long`/`int64_t` now parses to the DISTINCT
/// `Type::CLong` width (decy-frontend, PMAT-909) and maps to `c_longlong` —
/// no longer narrowed to `c_int`. The remaining ceiling is float/pointer/
/// string ABI tokens (decy's lexer still lacks them). `Bool → c_int` is a
/// lossy forward guard (decy never produces `Bool`); `Type::Unit` is handled
/// at the return position.
fn c_abi_type(ty: &Type) -> Option<&'static str> {
    match ty {
        Type::I64 | Type::Bool => Some("::std::os::raw::c_int"),
        // PMAT-909: a 64-bit C integer rides the `long long` ABI slot
        // (always ≥64-bit, unlike platform-variable `long`) — never
        // narrowed to `c_int`.
        Type::CLong => Some("::std::os::raw::c_longlong"),
        Type::F64 => Some("::std::os::raw::c_double"),
        _ => None,
    }
}

/// The native Rust type the safe wrapper speaks for an ABI-mappable `Type`
/// (callers use i64/f64; the wrapper casts to/from the C ABI type internally).
fn wrapper_native(ty: &Type) -> &'static str {
    match ty {
        Type::F64 => "f64",
        // I64, the Bool forward-guard, and the PMAT-909 CLong all ride an
        // `i64` native wrapper (CLong casts to/from `c_longlong`; I64 to/from
        // `c_int`).
        _ => "i64",
    }
}

/// PMAT-898 (Sprint-2 Tier 2): resolve each module's FFI-boundary `to_lang` from
/// the full dispatched module set. A single-file frontend can't see its siblings,
/// so `depyler-frontend::detect_ffi_boundaries` records a PROVISIONAL `to_lang`
/// (C, the canonical CPython-extension shape) for every relative import. With the
/// whole `Vec<Module>` in hand (the `xpile hybrid` CLI), rewrite each boundary's
/// `to_lang` to the `source_lang` of whichever sibling module actually DEFINES
/// the symbol. Consequences once `reconcile` runs:
///   - a relative import of a *Python* sibling becomes `Python → Python`, which
///     reconcile drops via its same-language skip (NOT a false FFI boundary);
///   - a relative import of a *C* sibling stays `Python → C` and resolves;
///   - a symbol no module defines is left as-is, so reconcile reports it
///     unresolved (the `manifest_completeness` invariant of C-FFI-CPYTHON-EXT).
///
/// Call this BEFORE [`FfiManifest::reconcile`].
pub fn resolve_boundary_to_langs(modules: &mut [Module]) {
    // symbol -> source_lang of the first module that exports it.
    let mut exporters: HashMap<String, SourceLang> = HashMap::new();
    for m in modules.iter() {
        for it in &m.items {
            if let Some(name) = item_exported_name(it) {
                exporters.entry(name.to_string()).or_insert(m.source_lang);
            }
        }
    }
    for m in modules.iter_mut() {
        for b in &mut m.ffi_boundaries {
            if let Some(&lang) = exporters.get(&b.symbol) {
                b.to_lang = lang;
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use xpile_meta_hir::{Block, Expr, Function, Type};

    fn module(name: &str, lang: SourceLang, boundaries: Vec<FfiBoundary>) -> Module {
        Module {
            name: name.to_string(),
            source_lang: lang,
            items: Vec::new(),
            ffi_boundaries: boundaries,
        }
    }

    /// A module of `lang` that DEFINES (exports) `symbol` as a nullary function —
    /// the FFI export side that symbol-level reconciliation requires.
    fn module_defining(name: &str, lang: SourceLang, symbol: &str) -> Module {
        Module {
            name: name.to_string(),
            source_lang: lang,
            items: vec![Item::Function(Function {
                name: symbol.to_string(),
                params: Vec::new(),
                return_type: Type::I64,
                body: Block {
                    stmts: Vec::new(),
                    trailing_return: Expr::LitInt(0),
                },
            })],
            ffi_boundaries: Vec::new(),
        }
    }

    fn boundary(from: SourceLang, to: SourceLang, symbol: &str) -> FfiBoundary {
        FfiBoundary {
            from_lang: from,
            to_lang: to,
            symbol: symbol.to_string(),
            signature: format!("{symbol}(...)"),
        }
    }

    /// A C module defining `symbol` as a function with the given params/return —
    /// the typed export side the shim emitter recovers signatures from.
    fn c_fn(name: &str, params: Vec<(&str, Type)>, ret: Type) -> Module {
        Module {
            name: name.to_string(),
            source_lang: SourceLang::C,
            items: vec![Item::Function(Function {
                name: name.to_string(),
                params: params
                    .into_iter()
                    .map(|(n, ty)| xpile_meta_hir::Param {
                        name: n.to_string(),
                        ty,
                        mutable: false,
                    })
                    .collect(),
                return_type: ret,
                body: Block {
                    stmts: Vec::new(),
                    trailing_return: Expr::LitInt(0),
                },
            })],
            ffi_boundaries: Vec::new(),
        }
    }

    /// Build [py-with-boundary, c-defining-fn], resolve + reconcile, and emit.
    fn emit_for(
        symbol: &str,
        params: Vec<(&str, Type)>,
        ret: Type,
    ) -> Result<String, FfiEmitError> {
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, symbol)],
            ),
            c_fn(symbol, params, ret),
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        manifest.emit_rust_shims(&modules)
    }

    #[test]
    fn emit_shims_extern_block_and_safe_wrapper() {
        let out = emit_for("square_sum", vec![("x", Type::I64)], Type::I64).expect("emits");
        assert!(out.contains("// xpile-contract: C-FFI-CPYTHON-EXT"));
        assert!(out.contains("extern \"C\" {"));
        assert!(out.contains("fn square_sum(x: ::std::os::raw::c_int) -> ::std::os::raw::c_int;"));
        assert!(out.contains("shim_"));
        assert!(out.contains("pub fn square_sum_shim(x: i64) -> i64 {"));
    }

    #[test]
    fn emit_shims_abi_honest_no_i64_in_extern_block() {
        // Regression guard: the extern block must use c_int (4-byte C int), never
        // a knowingly-wrong 8-byte i64.
        let out = emit_for("f", vec![("x", Type::I64)], Type::I64).expect("emits");
        let extern_block = out
            .split("extern \"C\" {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(extern_block.contains("c_int"));
        assert!(
            !extern_block.contains("i64"),
            "extern block must not declare i64: {extern_block}"
        );
    }

    #[test]
    fn c_abi_type_table() {
        assert_eq!(c_abi_type(&Type::I64), Some("::std::os::raw::c_int"));
        assert_eq!(c_abi_type(&Type::Bool), Some("::std::os::raw::c_int"));
        assert_eq!(c_abi_type(&Type::F64), Some("::std::os::raw::c_double"));
        // PMAT-909: a wider C integer is NOT narrowed to c_int.
        assert_eq!(
            c_abi_type(&Type::CLong),
            Some("::std::os::raw::c_longlong"),
            "long/int64_t must ride the 64-bit c_longlong ABI slot, not c_int"
        );
        assert_eq!(wrapper_native(&Type::CLong), "i64");
        for ty in [
            Type::Str,
            Type::List(Box::new(Type::I64)),
            Type::Dict(Box::new(Type::Str), Box::new(Type::I64)),
            Type::Set(Box::new(Type::I64)),
            Type::Tuple(vec![Type::I64]),
            Type::BigInt,
            Type::Optional(Box::new(Type::I64)),
            Type::Struct("P".into()),
            Type::ShellString,
            Type::ExitCode,
        ] {
            assert_eq!(c_abi_type(&ty), None, "{ty:?} must be refused");
        }
    }

    #[test]
    fn emit_shims_void_return_has_no_arrow() {
        let out = emit_for("log_it", vec![("x", Type::I64)], Type::Unit).expect("emits");
        assert!(out.contains("fn log_it(x: ::std::os::raw::c_int);"));
        assert!(!out.contains("fn log_it(x: ::std::os::raw::c_int) ->"));
    }

    #[test]
    fn emit_shims_refuses_unsupported_type() {
        let err = emit_for("takes_str", vec![("s", Type::Str)], Type::I64).expect_err("refused");
        assert!(err.to_string().contains("takes_str"));
        assert!(err.to_string().contains("Str"));
    }

    #[test]
    fn emit_shims_arity_and_names_faithful() {
        let out = emit_for(
            "triadd",
            vec![("a", Type::I64), ("b", Type::I64), ("c", Type::I64)],
            Type::I64,
        )
        .expect("emits");
        assert!(out.contains(
            "fn triadd(a: ::std::os::raw::c_int, b: ::std::os::raw::c_int, c: ::std::os::raw::c_int) -> ::std::os::raw::c_int;"
        ));
        let out0 = emit_for("now", vec![], Type::I64).expect("emits");
        assert!(out0.contains("fn now() -> ::std::os::raw::c_int;"));
    }

    /// Compile `src` as a standalone Rust lib under `-D warnings`, on BOTH
    /// edition 2021 and edition 2024. Returns `true` if rustc is unavailable
    /// (constrained CI skips the gate) or the source compiles under every
    /// edition. The emitted shim is meant to be dropped into a user crate of
    /// unknown edition — and `cargo new` defaults to 2024 — so a 2021-only gate
    /// would mask the bare-`extern "C"` regression (a hard error in 2024). `tag`
    /// keeps concurrent compile-gate tests off each other's temp files (a bare
    /// pid collides when tests run in parallel threads).
    fn rustc_lib_compiles(tag: &str, src: &str) -> bool {
        if std::process::Command::new("rustc")
            .arg("--version")
            .output()
            .is_err()
        {
            eprintln!("rustc unavailable — skipping compile gate");
            return true;
        }
        let dir = std::env::temp_dir();
        let pid = std::process::id();
        for edition in ["2021", "2024"] {
            let src_path = dir.join(format!("xpile_shim_gate_{tag}_{edition}_{pid}.rs"));
            let rlib = dir.join(format!("libxpile_shim_gate_{tag}_{edition}_{pid}.rlib"));
            std::fs::write(&src_path, src).expect("write shim");
            let status = std::process::Command::new("rustc")
                .args([
                    "--crate-type",
                    "lib",
                    "--edition",
                    edition,
                    "-D",
                    "warnings",
                ])
                .arg(&src_path)
                .arg("-o")
                .arg(&rlib)
                .status()
                .expect("spawn rustc");
            let _ = std::fs::remove_file(&src_path);
            let _ = std::fs::remove_file(&rlib);
            if !status.success() {
                eprintln!("emitted shim failed to compile under edition {edition}");
                return false;
            }
        }
        true
    }

    #[test]
    fn emit_shims_output_compiles_under_rustc() {
        // The load-bearing gate: the emitted shim is type/arity/ABI compile-
        // checkable with NO C object (the extern symbol stays unresolved at lib
        // build). Gated on rustc being spawnable so constrained CI skips it.
        let out = emit_for("square_sum", vec![("x", Type::I64)], Type::I64).expect("emits");
        assert!(
            rustc_lib_compiles("c", &out),
            "emitted C shim must compile under -D warnings"
        );
    }

    /// Build [driver-module-with-boundary, target-module-defining-symbol],
    /// resolve `to_lang` from the exporting sibling, reconcile, and emit — the
    /// generic shape behind the per-paradigm tests below.
    fn emit_cross(
        from: SourceLang,
        target: SourceLang,
        symbol: &str,
    ) -> Result<String, FfiEmitError> {
        let mut modules = vec![
            module("driver", from, vec![boundary(from, target, symbol)]),
            module_defining("target", target, symbol),
        ];
        resolve_boundary_to_langs(&mut modules);
        assert_eq!(
            modules[0].ffi_boundaries[0].to_lang, target,
            "to_lang should resolve to the exporting sibling"
        );
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        manifest.emit_rust_shims(&modules)
    }

    #[test]
    fn emit_shims_shell_boundary_emits_command_wrapper() {
        // A Python→Shell boundary lowers to a real subprocess shim — no extern
        // block, no `unsafe`, just std::process::Command (shell's true ABI).
        let out = emit_cross(SourceLang::Python, SourceLang::Shell, "deploy").expect("emits");
        assert!(out.contains(
            "pub fn deploy_shim(args: &[&str]) -> ::std::io::Result<::std::process::Output>"
        ));
        assert!(out.contains("::std::process::Command::new(\"deploy\").args(args).output()"));
        assert!(
            !out.contains("extern \"C\""),
            "shell is not a C-ABI callee: {out}"
        );
        // PMAT-907: the shell shim now cites its governing contract — the
        // argv-passthrough + exit-code-propagation strategy is no longer
        // capability-ahead-of-contract.
        assert!(
            out.contains("// xpile-contract: C-FFI-SHELL-SUBPROCESS"),
            "shell shim must cite C-FFI-SHELL-SUBPROCESS: {out}"
        );
        assert!(
            rustc_lib_compiles("shell", &out),
            "emitted shell shim must compile under -D warnings"
        );
    }

    #[test]
    fn emit_shims_cpp_boundary_reports_pybind11_gap() {
        let err = emit_cross(SourceLang::Python, SourceLang::Cpp, "g").expect_err("refused");
        assert!(err.to_string().contains("pybind11"), "{err}");
        assert!(err.to_string().contains('g'));
    }

    #[test]
    fn emit_shims_cuda_boundary_reports_host_launch_gap() {
        let err = emit_cross(SourceLang::Python, SourceLang::Cuda, "k").expect_err("refused");
        assert!(err.to_string().contains("cudaLaunchKernel"), "{err}");
    }

    #[test]
    fn emit_shims_python_boundary_reports_pyo3_gap() {
        // from != to (Rust→Python), else reconcile drops it as same-language.
        let err = emit_cross(SourceLang::Rust, SourceLang::Python, "embed").expect_err("refused");
        assert!(err.to_string().contains("pyo3"), "{err}");
    }

    #[test]
    fn emit_shims_lean_boundary_is_proof_lane_not_shim() {
        let err = emit_cross(SourceLang::Python, SourceLang::Lean, "thm").expect_err("refused");
        assert!(err.to_string().contains("proof lane"), "{err}");
    }

    #[test]
    fn emit_shims_ruchy_boundary_emits_direct_call_forwarder() {
        // PMAT-905: a Ruchy boundary lowers to a real same-crate direct-call
        // forwarder — no extern block, no `unsafe`, no contract citation, just a
        // plain in-crate call (Ruchy → Rust). `module_defining` exports `helper`
        // as a nullary `-> i64`.
        let out = emit_cross(SourceLang::Python, SourceLang::Ruchy, "helper").expect("emits");
        assert!(out.contains("pub fn helper_shim() -> i64 {"), "{out}");
        assert!(out.contains("helper()"), "{out}");
        assert!(
            !out.contains("extern \"C\""),
            "a direct call is not FFI: {out}"
        );
        assert!(
            !out.contains("unsafe"),
            "a direct call needs no unsafe: {out}"
        );
        assert!(
            !out.contains("xpile-contract:"),
            "direct call is capability-ahead-of-contract (no citation): {out}"
        );
        // Compiles when the same-crate callee is in scope (the real workspace
        // context: main.rs defines `helper`, the shim forwards to it). Appended
        // AFTER the shim so the file's `#![allow(dead_code)]` inner attribute
        // stays at the top.
        let with_callee = format!("{out}\nfn helper() -> i64 {{ 0 }}\n");
        assert!(
            rustc_lib_compiles("ruchy", &with_callee),
            "emitted direct-call shim must compile under -D warnings"
        );
    }

    #[test]
    fn emit_shims_rust_boundary_emits_direct_call_forwarder() {
        let out = emit_cross(SourceLang::Python, SourceLang::Rust, "helper").expect("emits");
        assert!(out.contains("pub fn helper_shim() -> i64 {"), "{out}");
        assert!(out.contains("helper()"), "{out}");
        assert!(!out.contains("extern \"C\""), "{out}");
        assert!(!out.contains("unsafe"), "{out}");
    }

    #[test]
    fn emit_direct_shim_maps_native_param_and_return_types() {
        // A Rust boundary with native (non-C-ABI) param + return types: the
        // forwarder speaks them verbatim (i64/f64/String/bool) — no `as c_int`
        // marshalling, unlike the C arm.
        let mut modules = vec![
            module(
                "driver",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::Rust, "mix")],
            ),
            Module {
                name: "lib".into(),
                source_lang: SourceLang::Rust,
                items: vec![Item::Function(Function {
                    name: "mix".into(),
                    params: vec![
                        xpile_meta_hir::Param {
                            name: "a".into(),
                            ty: Type::I64,
                            mutable: false,
                        },
                        xpile_meta_hir::Param {
                            name: "b".into(),
                            ty: Type::F64,
                            mutable: false,
                        },
                        xpile_meta_hir::Param {
                            name: "s".into(),
                            ty: Type::Str,
                            mutable: false,
                        },
                    ],
                    return_type: Type::Bool,
                    body: Block {
                        stmts: Vec::new(),
                        trailing_return: Expr::LitInt(0),
                    },
                })],
                ffi_boundaries: Vec::new(),
            },
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        let out = manifest.emit_rust_shims(&modules).expect("emits");
        assert!(
            out.contains("pub fn mix_shim(a: i64, b: f64, s: String) -> bool {"),
            "{out}"
        );
        assert!(out.contains("mix(a, b, s)"), "{out}");
    }

    #[test]
    fn emit_direct_shim_refuses_non_std_dep_type() {
        // A Rust boundary returning BigInt: its native lowering needs the
        // xpile_bigint dep the hybrid workspace does not pin, so the forwarder is
        // refused with a named reason rather than emitting an unbuildable shim.
        let mut modules = vec![
            module(
                "driver",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::Rust, "big")],
            ),
            Module {
                name: "lib".into(),
                source_lang: SourceLang::Rust,
                items: vec![Item::Function(Function {
                    name: "big".into(),
                    params: Vec::new(),
                    return_type: Type::BigInt,
                    body: Block {
                        stmts: Vec::new(),
                        trailing_return: Expr::LitInt(0),
                    },
                })],
                ffi_boundaries: Vec::new(),
            },
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        let err = manifest.emit_rust_shims(&modules).expect_err("refused");
        assert!(err.to_string().contains("BigInt"), "{err}");
        assert!(err.to_string().contains("big"), "{err}");
    }

    #[test]
    fn emit_shims_f64_boundary_maps_c_double() {
        // The only non-integer ABI slot + the only f64 wrapper-native branch:
        // c_double extern, f64 wrapper, `__r as f64` return. Compiles end-to-end.
        let out = emit_for("scale", vec![("x", Type::F64)], Type::F64).expect("emits");
        assert!(out.contains("fn scale(x: ::std::os::raw::c_double) -> ::std::os::raw::c_double;"));
        assert!(out.contains("pub fn scale_shim(x: f64) -> f64 {"));
        assert!(out.contains("__r as f64"));
        assert!(
            rustc_lib_compiles("f64", &out),
            "emitted f64 shim must compile under -D warnings"
        );
    }

    #[test]
    fn emit_shims_clong_boundary_maps_c_longlong() {
        // PMAT-909: a `long`/`int64_t` C boundary rides the 64-bit
        // c_longlong ABI slot (NOT narrowed to c_int) with an i64 wrapper
        // — the decy wider-int lift. Compiles end-to-end under -D warnings.
        let out = emit_for("widen", vec![("x", Type::CLong)], Type::CLong).expect("emits");
        assert!(
            out.contains("fn widen(x: ::std::os::raw::c_longlong) -> ::std::os::raw::c_longlong;"),
            "long boundary must use c_longlong, not c_int:\n{out}"
        );
        assert!(out.contains("pub fn widen_shim(x: i64) -> i64 {"));
        assert!(out.contains("x as ::std::os::raw::c_longlong"));
        assert!(out.contains("__r as i64"));
        // A wider-int boundary must NEVER silently narrow to c_int.
        let extern_block = out
            .split("extern \"C\" {")
            .nth(1)
            .unwrap()
            .split('}')
            .next()
            .unwrap();
        assert!(
            !extern_block.contains("c_int"),
            "a CLong boundary must not narrow to c_int:\n{extern_block}"
        );
        assert!(
            rustc_lib_compiles("clong", &out),
            "emitted c_longlong shim must compile under -D warnings"
        );
    }

    #[test]
    fn emit_shims_c_symbol_that_is_a_const_is_refused() {
        // A C module can export the symbol as an Item::Const — reconcile resolves
        // it (item_exported_name matches consts), but it is not callable, so the C
        // arm surfaces the gap rather than emitting a bogus extern fn.
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "TABLE")],
            ),
            Module {
                name: "cmod".to_string(),
                source_lang: SourceLang::C,
                items: vec![Item::Const {
                    name: "TABLE".to_string(),
                    ty: Type::I64,
                    value: Expr::LitInt(0),
                }],
                ffi_boundaries: Vec::new(),
            },
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("const symbol reconciles");
        let err = manifest
            .emit_rust_shims(&modules)
            .expect_err("a const is not a callable shim target");
        assert!(err.to_string().contains("TABLE"));
        assert!(err.to_string().contains("not a function"), "{err}");
    }

    #[test]
    fn emit_shims_is_all_or_nothing_across_paradigms() {
        // A manifest with a shimmable C boundary AND an unshimmable C++ boundary
        // emits NOTHING — a half-shimmed hybrid build is not a build.
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![
                    boundary(SourceLang::Python, SourceLang::C, "ok_c"),
                    boundary(SourceLang::Python, SourceLang::Cpp, "bad_cpp"),
                ],
            ),
            c_fn("ok_c", vec![("x", Type::I64)], Type::I64),
            module_defining("cpp", SourceLang::Cpp, "bad_cpp"),
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        let err = manifest
            .emit_rust_shims(&modules)
            .expect_err("one bad boundary fails all");
        assert!(err.to_string().contains("bad_cpp"));
        assert!(err.to_string().contains("pybind11"));
    }

    #[test]
    fn reconcile_pairs_boundary_when_target_defines_symbol() {
        let modules = vec![
            module(
                "foo",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "sum")],
            ),
            module_defining("_foo_core", SourceLang::C, "sum"),
        ];
        let manifest = FfiManifest::reconcile(&modules).expect("resolves");
        assert_eq!(manifest.entries.len(), 1);
        assert_eq!(manifest.entries[0].symbol, "sum");
        assert_eq!(manifest.entries[0].from_lang, SourceLang::Python);
        assert_eq!(manifest.entries[0].to_lang, SourceLang::C);
        assert!(manifest.entries[0].shim_id.starts_with("shim_"));
    }

    #[test]
    fn reconcile_fails_when_target_lang_absent() {
        let modules = vec![module(
            "foo",
            SourceLang::Python,
            vec![boundary(SourceLang::Python, SourceLang::C, "sum")],
        )];
        let err = FfiManifest::reconcile(&modules).expect_err("unresolved");
        assert_eq!(err.unresolved.len(), 1);
        assert!(err.to_string().contains("sum"));
        assert!(err.to_string().contains("dispatched set"));
    }

    #[test]
    fn reconcile_fails_when_symbol_not_defined() {
        // The C module is PRESENT but does not export `sum` (it defines `other`)
        // — symbol-level reconciliation must still fail, with a symbol-specific
        // diagnostic distinct from the language-absent case.
        let modules = vec![
            module(
                "foo",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "sum")],
            ),
            module_defining("_foo_core", SourceLang::C, "other"),
        ];
        let err = FfiManifest::reconcile(&modules).expect_err("symbol not defined");
        assert_eq!(err.unresolved.len(), 1);
        assert!(err.to_string().contains("defines `sum`"));
    }

    #[test]
    fn reconcile_ignores_same_language_boundaries_and_empty() {
        let modules = vec![module(
            "foo",
            SourceLang::Python,
            vec![boundary(SourceLang::Python, SourceLang::Python, "local")],
        )];
        let manifest = FfiManifest::reconcile(&modules).expect("no cross-lang boundary");
        assert!(manifest.entries.is_empty());
        assert!(FfiManifest::reconcile(&[]).unwrap().entries.is_empty());
    }

    #[test]
    fn shim_id_is_deterministic() {
        let b = boundary(SourceLang::Python, SourceLang::C, "sum");
        assert_eq!(shim_id(&b), shim_id(&b));
    }

    #[test]
    fn resolve_to_python_sibling_drops_false_boundary() {
        // A relative import of a PYTHON sibling is mislabeled Python->C by the
        // single-file frontend; after resolution it becomes Python->Python, which
        // reconcile drops (not a real FFI boundary).
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "helper")],
            ),
            module_defining("helpers", SourceLang::Python, "helper"),
        ];
        resolve_boundary_to_langs(&mut modules);
        assert_eq!(modules[0].ffi_boundaries[0].to_lang, SourceLang::Python);
        let manifest = FfiManifest::reconcile(&modules).expect("same-lang drops");
        assert!(manifest.entries.is_empty());
    }

    #[test]
    fn resolve_to_c_sibling_keeps_cross_language_boundary() {
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "square_sum")],
            ),
            module_defining("_core", SourceLang::C, "square_sum"),
        ];
        resolve_boundary_to_langs(&mut modules);
        assert_eq!(modules[0].ffi_boundaries[0].to_lang, SourceLang::C);
        let manifest = FfiManifest::reconcile(&modules).expect("resolves");
        assert_eq!(manifest.entries.len(), 1);
        assert_eq!(manifest.entries[0].to_lang, SourceLang::C);
    }

    #[test]
    fn resolve_leaves_undefined_symbol_unchanged() {
        // No module defines `missing` → to_lang stays as the provisional C, so
        // reconcile reports it unresolved.
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "missing")],
            ),
            module_defining("_core", SourceLang::C, "present"),
        ];
        resolve_boundary_to_langs(&mut modules);
        assert_eq!(modules[0].ffi_boundaries[0].to_lang, SourceLang::C);
        assert!(FfiManifest::reconcile(&modules).is_err());
    }

    #[test]
    fn emit_hybrid_workspace_writes_buildable_layout() {
        // File-layout assertions only (no cargo build — that's the cc+cargo-gated
        // integration test in the xpile crate).
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::C, "square_sum")],
            ),
            c_fn("square_sum", vec![("x", Type::I64)], Type::I64),
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");

        let dir = std::env::temp_dir().join(format!("xpile_ws_unit_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        manifest
            .emit_hybrid_workspace(
                &modules,
                &[(
                    "_core.c".to_string(),
                    "int square_sum(int x){return x*x;}\n".to_string(),
                )],
                "pub fn main() {}\n",
                &dir,
            )
            .expect("emits workspace");

        assert!(dir.join("Cargo.toml").exists());
        assert!(dir.join("build.rs").exists());
        assert_eq!(
            std::fs::read_to_string(dir.join("csrc/_core.c")).unwrap(),
            "int square_sum(int x){return x*x;}\n"
        );
        let main_rs = std::fs::read_to_string(dir.join("src/main.rs")).unwrap();
        assert!(main_rs.contains("pub fn main()") && main_rs.contains("mod ffi_shims;"));
        let shims = std::fs::read_to_string(dir.join("src/ffi_shims.rs")).unwrap();
        assert!(shims.contains("pub fn square_sum_shim") && shims.contains("unsafe extern \"C\""));
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn emit_hybrid_workspace_propagates_unshimmable_boundary() {
        // An unshimmable (C++) boundary fails the workspace emit too — fail-loud,
        // no half-built workspace.
        let mut modules = vec![
            module(
                "app",
                SourceLang::Python,
                vec![boundary(SourceLang::Python, SourceLang::Cpp, "g")],
            ),
            module_defining("cpp", SourceLang::Cpp, "g"),
        ];
        resolve_boundary_to_langs(&mut modules);
        let manifest = FfiManifest::reconcile(&modules).expect("reconciles");
        let dir = std::env::temp_dir().join(format!("xpile_ws_unit_bad_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let err = manifest
            .emit_hybrid_workspace(&modules, &[], "pub fn main() {}\n", &dir)
            .expect_err("c++ boundary is unshimmable");
        assert!(matches!(err, WorkspaceEmitError::Shims(_)));
        assert!(err.to_string().contains("pybind11"));
    }
}
